import 'package:flutter/material.dart';
import '../../core/app_settings_controller.dart';
import '../../core/theme.dart';
import 'session_controller.dart';
import '../leaves/leave_approvals_screen.dart';
import 'user_management_screen.dart';

class ProfileSettingsScreen extends StatefulWidget { const ProfileSettingsScreen({super.key,required this.session,required this.settings}); final SessionController session;final AppSettingsController settings;@override State<ProfileSettingsScreen> createState()=>_ProfileSettingsScreenState(); }
class _ProfileSettingsScreenState extends State<ProfileSettingsScreen>{bool biometric=false;bool twoFactor=false;@override Widget build(BuildContext context){final user=widget.session.user??{};return Scaffold(backgroundColor:const Color(0xFFF5F8FC),appBar:AppBar(backgroundColor:const Color(0xFFF5F8FC),title:const Text('Profile & settings',style:TextStyle(color:Color(0xFF0F2440),fontWeight:FontWeight.w800))),body:ListView(padding:const EdgeInsets.all(20),children:[Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(gradient:const LinearGradient(colors:[HRMateTheme.blue,HRMateTheme.green]),borderRadius:BorderRadius.circular(22)),child:Row(children:[const CircleAvatar(radius:30,backgroundColor:Colors.white,child:Icon(Icons.person,color:HRMateTheme.blue,size:34)),const SizedBox(width:14),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(user['name']?.toString()??'User',style:const TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.w900)),Text(user['role']?.toString()??'',style:const TextStyle(color:Colors.white70))])])),const SizedBox(height:20),_tile(Icons.person_outline,'My profile'),SwitchListTile(value:biometric,onChanged:(v)=>setState(()=>biometric=v),title:const Text('Biometric login'),secondary:const Icon(Icons.fingerprint)),_tile(Icons.language,'Language',subtitle:'Punjabi'),_tile(Icons.brightness_6_outlined,'Appearance',subtitle:widget.settings.themeMode.name),_tile(Icons.format_size,'Text size',subtitle:'${widget.settings.textScale}x'),SwitchListTile(value:twoFactor,onChanged:(v)=>setState(()=>twoFactor=v),title:const Text('Two-factor authentication'),secondary:const Icon(Icons.security_outlined)),if((user['role']??'')!='employee')Card(child:ListTile(leading:const Icon(Icons.approval_outlined,color:HRMateTheme.blue),title:const Text('Leave approvals'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>LeaveApprovalsScreen(session:widget.session))))),if(user['role']=='super_admin')Card(child:ListTile(leading:const Icon(Icons.manage_accounts_outlined,color:HRMateTheme.blue),title:const Text('User management'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>UserManagementScreen(session:widget.session))))),const SizedBox(height:14),OutlinedButton.icon(onPressed:widget.session.logout,style:OutlinedButton.styleFrom(foregroundColor:const Color(0xFFDB3131),side:const BorderSide(color:Color(0xFFDB3131)),padding:const EdgeInsets.symmetric(vertical:16)),icon:const Icon(Icons.logout),label:const Text('Sign out'))]));}Widget _tile(IconData icon,String title,{String? subtitle})=>Card(child:ListTile(leading:Icon(icon,color:HRMateTheme.blue),title:Text(title),subtitle:subtitle==null?null:Text(subtitle),trailing:const Icon(Icons.chevron_right)));}
