import { Router } from 'express';
import { db } from '../db/index.js';
import { authRequired, requirePerm } from '../middleware/auth.js';
import { audit } from '../helpers.js';
const router=Router(); router.use(authRequired);
router.get('/',requirePerm('employees.view'),(req,res)=>res.json({employees: db.prepare('SELECT * FROM employees WHERE active=1 ORDER BY name').all()}));
router.get('/:id',requirePerm('employees.view'),(req,res)=>{ const employee=db.prepare('SELECT * FROM employees WHERE id=? AND active=1').get(req.params.id); if(!employee) return res.status(404).json({error:'Employee not found'}); const attendance=db.prepare('SELECT * FROM attendance WHERE employee_id=? ORDER BY attendance_date DESC LIMIT 31').all(employee.id); const balance=db.prepare('SELECT * FROM leave_balances WHERE employee_id=?').get(employee.id); res.json({employee,attendance,balance}); });
router.patch('/:id',requirePerm('employees.manage'),audit({action:'employee.updated',entityType:'employee',entityId:(req)=>req.params.id,title:'Employee updated',body:'An employee profile was updated.'},(req,res)=>{ const current=db.prepare('SELECT * FROM employees WHERE id=? AND active=1').get(req.params.id); if(!current) return res.status(404).json({error:'Employee not found'}); const values={...current,...req.body}; db.prepare('UPDATE employees SET name=?,phone=?,role_title=?,department=?,shift_name=?,join_date=?,photo_url=?,employee_code=? WHERE id=?').run(values.name,values.phone,values.roleTitle??values.role_title,values.department,values.shiftName??values.shift_name,values.joinDate??values.join_date,values.photoUrl??values.photo_url,values.employeeCode??values.employee_code,current.id); res.json({employee:db.prepare('SELECT * FROM employees WHERE id=?').get(current.id)}); }));
router.post('/',requirePerm('employees.manage'),audit({action:'employee.created',entityType:'employee',entityId:()=>null,title:'Employee added',body:'A new employee was added to HRMate.'},(req,res)=>{
 const {name,phone,roleTitle,department,shiftName,joinDate,photoUrl,employeeCode,userId}=req.body; if(!name) return res.status(400).json({error:'Employee name is required'});
 if (userId && !db.prepare('SELECT id FROM users WHERE id=?').get(userId)) return res.status(400).json({error:'Linked user not found'});
 const result=db.prepare('INSERT INTO employees (user_id,name,phone,role_title,department,shift_name,join_date,photo_url,employee_code) VALUES (?,?,?,?,?,?,?,?,?)').run(userId??null,name,phone??null,roleTitle??null,department??null,shiftName??null,joinDate??null,photoUrl??null,employeeCode??null); db.prepare('INSERT OR IGNORE INTO leave_balances (employee_id) VALUES (?)').run(result.lastInsertRowid); res.status(201).json({id:result.lastInsertRowid});
})); export default router;
