import 'package:flutter/material.dart';
import '../../core/api_client.dart';
import '../../core/theme.dart';
import '../auth/session_controller.dart';
import 'add_employee_screen.dart';
import 'employee_profile_screen.dart';

class EmployeesScreen extends StatefulWidget { const EmployeesScreen({super.key,required this.session}); final SessionController session; @override State<EmployeesScreen> createState()=>_EmployeesScreenState(); }
class _EmployeesScreenState extends State<EmployeesScreen>{bool loading=true;String? error;List<dynamic> employees=[];String filter='All';@override void initState(){super.initState();load();}Future<void> load()async{setState(()=>loading=true);try{final response=await widget.session.employees();if(mounted)setState(()=>employees=response['employees'] as List<dynamic>? ?? []);}on ApiException catch(e){if(mounted)setState(()=>error=e.message);}finally{if(mounted)setState(()=>loading=false);}}@override Widget build(BuildContext context){final visible=employees.where((e)=>filter=='All'||e['department']==filter).toList();return Scaffold(backgroundColor:const Color(0xFFF5F8FC),appBar:AppBar(backgroundColor:const Color(0xFFF5F8FC),title:const Text('Employees',style:TextStyle(color:Color(0xFF0F2440),fontWeight:FontWeight.w800))),floatingActionButton:FloatingActionButton(onPressed:() async { final created=await Navigator.of(context).push<bool>(MaterialPageRoute(builder:(_)=>AddEmployeeScreen(session:widget.session))); if(created==true)load(); },backgroundColor:HRMateTheme.blue,child:const Icon(Icons.add)),body:RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(20),children:[TextField(decoration:InputDecoration(hintText:'Search name, department…',prefixIcon:const Icon(Icons.search),filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:BorderSide.none))),const SizedBox(height:12),Wrap(spacing:8,children:['All','Production','Quality','Warehouse'].map((x)=>ChoiceChip(label:Text(x),selected:filter==x,onSelected:(_)=>setState(()=>filter=x))).toList()),const SizedBox(height:16),if(loading)const Padding(padding:EdgeInsets.all(50),child:Center(child:CircularProgressIndicator()))else if(error!=null)Text(error!)else for(final e in visible)_EmployeeCard(employee:e as Map<String,dynamic>,onTap:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>EmployeeProfileScreen(session:widget.session,employeeId:e['id'] as int))))])));}}
class _EmployeeCard extends StatelessWidget{const _EmployeeCard({required this.employee,required this.onTap});final Map<String,dynamic> employee;final VoidCallback onTap;@override Widget build(BuildContext context)=>Card(child:ListTile(onTap:onTap,leading:CircleAvatar(backgroundColor:const Color(0xFFE4EEFF),child:Text((employee['name']?.toString()??'E').substring(0,1))),title:Text(employee['name']?.toString()??''),subtitle:Text('${employee['department']??'—'} · ${employee['shift_name']??'—'}'),trailing:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(employee['employee_code']?.toString()??'',style:const TextStyle(color:HRMateTheme.blue,fontSize:11)),const Text('● Present',style:TextStyle(color:HRMateTheme.green,fontSize:10))])));}
